name: Codex Review 🤖
on: [pull_request]

permissions:
  contents: read
  pull-requests: write  # Permissão ESSENCIAL para comentar
  issues: write         # Permissão adicional que pode ser necessária

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar identidade do bot
        run: |
          git config --global user.name "codex1337-bot"
          git config --global user.email "lojashopify1337@gmail.com"

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install PyGithub requests python-dotenv

      - name: Executar análise
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use o token padrão do GitHub Actions
        run: |
          python .github/workflows/analyze_code.py
          python .github/workflows/post_comments.py
